"""Versioned bounds shared by Profile Delegate event writers and spectators."""
from __future__ import annotations

EVENT_SCHEMA_VERSION = 1
EVENT_JOURNAL_MAX_BYTES = 1_048_576
EVENT_RECORD_MAX_BYTES = 16_384
EVENT_TEXT_FRAGMENT_MAX_CHARS = 2_048
EVENT_MESSAGE_MAX_CHARS = 32_768
EVENT_IDENTIFIER_MAX_CHARS = 128
EVENT_METADATA_MAX_CHARS = 200
EVENT_TIMESTAMP_MAX_CHARS = 64
